name: CI

on:
    push:
        branches: [ master ]
    
jobs:
    deploy:
        runs-on: self-hosted
    
    strategy: 
        matrix:
            node-version: [12.x]
            
    steps:
      - name: Use node
        uses: actions/setup-node@v2
        with:
            node-version: '12.13.0'
            check-latest: true
    - name: Install dependencies
      run: npm ci
